language: bash
dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

before_script: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  kcov --version

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('testbench'), host='%', password_last_changed=FROM_UNIXTIME(1523829600) where User='root'; update user set plugin='mysql_native_password'; delete from user where User != 'root' OR host != '%'; delete from user where User = 'sys'; FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - "[ -f shunit2-2.0.3.tgz ] || wget http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz -O shunit2-2.0.3.tgz"
  - tar zxf shunit2-2.0.3.tgz && rm shunit2-2.0.3.tgz
  - chmod +x ./shunit2-2.0.3/src/shell/shunit2

script:
    - kcov --include-pattern=backup.sh,tests.sh --exclude-pattern=coverage coverage ./tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
